<?php

namespace AppBundle\Repository;

/**
 * LikeEquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeEquipeRepository extends \Doctrine\ORM\EntityRepository
{
}
