app_annoncecollocation:
    resource: "@CollocationBundle/Resources/config/routing/annoncecollocation.yml"
    prefix:   /annoncecollocation

app_reclamation:
    resource: "@CollocationBundle/Resources/config/routing/reclamation.yml"
    prefix:   /reclamation

